# Site wide configuration

title: "Amith Raravi"
description: "Reader. Coder. Play a bit of chess, a movie here, a road-trip there :)"
# 120x120 px default image used for Twitter summary card
logo: /images/amith-bio.png
# 400x250 px default teaser image used in image archive grid
teaser: 400x250.gif
locale: en
repository: raravi/amithraravi2.com
staticman:
  branch: master
#comments:
#  receiver: https://staticman-amith.azurewebsites.net/api/PostComment

# Change this before publishing to Live Server!!!
url: https://www.amithraravi.com
# url: http://localhost:4000
feed:
  path: atom.xml

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg
  # 160x160 px image for author byline
  disqus-shortname:

twitter:
  username: amith_raravi

social:
  name: Amith Raravi
  links:
    - https://www.twitter.com/amith_raravi
    - https://www.facebook.com/amith.raravi
    - https://www.linkedin.com/in/amith-raravi-82b525139
    - https://plus.google.com/+AmithRaravi
    - https://github.com/raravi
    - https://www.instagram.com/the.raravi.chronicles
    - https://forum.xda-developers.com/member.php?u=4214466
    - https://www.goodreads.com/user/show/12212283-amith-raravi
    - https://runkeeper.com/user/raravi

include:
  - .htaccess
  - _pages

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package-lock.json
  - package.json
  - spec
  - tmp
  - staticman.yml
