# Site wide configuration

title: "Amith Raravi"
description: "Reader. Coder. Play a bit of chess, a movie here, a road-trip there :)"
# 120x120 px default image used for Twitter summary card
logo: /images/amith-bio.jpg
# 400x250 px default teaser image used in image archive grid
teaser: 400x250.gif
locale: en
repository: raravi/amithraravi2.com

# Change this before publishing to Live Server!!!
url: https://www.amithraravi.com
imagekiturl: https://ik.imagekit.io/raravi
# url: http://localhost:4000
#feed:
#  path: atom.xml

# IMAGES folder
# should have '/' for root!
# usage: {{site.url}}{{site.images}}image.jpg
images: /images/

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-feed
#  - jekyll-seo-tag

# Site owner
owner:
  name: Amith Raravi
  email: amith.raravi@gmail.com
  twitter:
    url: https://www.twitter.com
    username: amith_raravi
  facebook:
    url: https://www.facebook.com
    username: amith.raravi
  linkedin:
    url: https://www.linkedin.com
    username: in/amith-raravi-82b525139
  googleplus:
    url: https://plus.google.com
    username: +AmithRaravi
  github:
    url: https://github.com
    username: raravi
  instagram:
    url: https://www.instagram.com
    username: the.raravi.chronicles
  xda:
    url: https://forum.xda-developers.com
    username: member.php?u=4214466
  goodreads:
    url: https://www.goodreads.com
    username: user/show/12212283-amith-raravi
  runkeeper:
    url: https://runkeeper.com
    username: user/raravi
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg
  # 160x160 px image for author byline
  disqus-shortname:

social:
  name: Amith Raravi
  links:
    - https://www.twitter.com/amith_raravi
    - https://www.facebook.com/amith.raravi
    - https://www.linkedin.com/in/amith-raravi-82b525139
    - https://plus.google.com/+AmithRaravi
    - https://github.com/raravi
    - https://www.instagram.com/the.raravi.chronicles
    - https://forum.xda-developers.com/member.php?u=4214466
    - https://www.goodreads.com/user/show/12212283-amith-raravi
    - https://runkeeper.com/user/raravi

include:
  - .htaccess
  - _pages

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .DS_Store
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package-lock.json
  - package.json
  - spec
  - tmp
  - staticman.yml
  - webpack.config.js
  - js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts
