defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build1:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.6
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-favicon  \
              --check-html \
              --disable-external
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  build2:
    <<: *defaults
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run webpack
          command: npm run webpack
      - run:
          name: Run purgecss
          command: npm run purgecss
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Remove _site/css folder
          command: rm -r _site/css
      - run:
          name: Deploy _site/ folder over SSH
          command: |
            rsync -a --progress --delete _site/ dh_hc94wb@templer.dreamhost.com:/home/dh_hc94wb/amithraravi.com/ --exclude=/.git/ --exclude=/cgi-bin/ --exclude=/.well-known/ --exclude=/.htaccess --exclude=/.gitignore --exclude=/entry*.yml --exclude=/google*.html --exclude=/stackms.php
      - run:
          name: Deploy dist/ folder over SSH
          command: |
            rsync -a --progress --delete dist/ dh_hc94wb@templer.dreamhost.com:/home/dh_hc94wb/amithraravi.com/dist/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build1
      - build2:
          requires:
            - build1
      - deploy:
          requires:
            - build2
          filters:
            branches:
              only: master
